version: '3.9'

services:
  ai-lab:
    image: m0ahmedd/cuda12cudnn22:v2
    restart: always
    volumes:
      - ./jupyter_mount:/workspace
      # - ./jupyter_config:/root/.jupyter/
      - ./wandb_mount/wandb/config:/root/.config/wandb
    ports:
      - '8888:8888'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]